services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_ORIGIN: http://localhost, https://focus-ai-kohl.vercel.app
    restart: unless-stopped

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
