version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dev
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5001
    command: pnpm run dev

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: pnpm run dev
    depends_on:
      - server
